spring:
  application:
    name: account-service
#  config:
#    activate:
#      on-profile:
#        - prod
server:
  port: 8082

message: Hello from the other side

messageDev: Hello from the other side DEV message